# Generated by Django 3.1.4 on 2020-12-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0003_auto_20201221_1848'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='note',
            constraint=models.UniqueConstraint(fields=('diary', 'title'), name='unique_notes'),
        ),
    ]
