# Generated by Django 3.1.4 on 2020-12-28 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0005_auto_20201223_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='last_update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
